<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container58IxxA3\App_KernelENVDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container58IxxA3/App_KernelENVDebugContainer.php') {
    touch(__DIR__.'/Container58IxxA3.legacy');

    return;
}

if (!\class_exists(App_KernelENVDebugContainer::class, false)) {
    \class_alias(\Container58IxxA3\App_KernelENVDebugContainer::class, App_KernelENVDebugContainer::class, false);
}

return new \Container58IxxA3\App_KernelENVDebugContainer([
    'container.build_hash' => '58IxxA3',
    'container.build_id' => '1e5ca42a',
    'container.build_time' => 1641972562,
], __DIR__.\DIRECTORY_SEPARATOR.'Container58IxxA3');
