#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index.index:
    path: / 
    controller: App\Controller\IndexController::index

product.index:
    path: /product 
    controller: App\Controller\ProductController::index

product.show:
    path: /product/{id} 
    controller: App\Controller\ProductController::show

cart.index:
    path: /cart
    controller: App\Controller\CartController::index

cart.add:
    path: /cart/add/{id} 
    controller: App\Controller\CartController::add

cart.delete:
    path: /cart/delete/{id} 
    controller: App\Controller\CartController::delete