<?php

namespace ContainerXNRxWxE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KrS_NrzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.krS.nrz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.krS.nrz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CartController::add' => ['privates', '.service_locator.IWqJRDA', 'get_ServiceLocator_IWqJRDAService', true],
            'App\\Controller\\CartController::delete' => ['privates', '.service_locator.aI7umW_', 'get_ServiceLocator_AI7umWService', true],
            'App\\Controller\\CartController::index' => ['privates', '.service_locator.aI7umW_', 'get_ServiceLocator_AI7umWService', true],
            'App\\Controller\\IndexController::index' => ['privates', '.service_locator.JnHMbEU', 'get_ServiceLocator_JnHMbEUService', true],
            'App\\Controller\\ProductController::index' => ['privates', '.service_locator.JnHMbEU', 'get_ServiceLocator_JnHMbEUService', true],
            'App\\Controller\\ProductController::show' => ['privates', '.service_locator.JnHMbEU', 'get_ServiceLocator_JnHMbEUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\CartController:add' => ['privates', '.service_locator.IWqJRDA', 'get_ServiceLocator_IWqJRDAService', true],
            'App\\Controller\\CartController:delete' => ['privates', '.service_locator.aI7umW_', 'get_ServiceLocator_AI7umWService', true],
            'App\\Controller\\CartController:index' => ['privates', '.service_locator.aI7umW_', 'get_ServiceLocator_AI7umWService', true],
            'App\\Controller\\IndexController:index' => ['privates', '.service_locator.JnHMbEU', 'get_ServiceLocator_JnHMbEUService', true],
            'App\\Controller\\ProductController:index' => ['privates', '.service_locator.JnHMbEU', 'get_ServiceLocator_JnHMbEUService', true],
            'App\\Controller\\ProductController:show' => ['privates', '.service_locator.JnHMbEU', 'get_ServiceLocator_JnHMbEUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\CartController::add' => '?',
            'App\\Controller\\CartController::delete' => '?',
            'App\\Controller\\CartController::index' => '?',
            'App\\Controller\\IndexController::index' => '?',
            'App\\Controller\\ProductController::index' => '?',
            'App\\Controller\\ProductController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CartController:add' => '?',
            'App\\Controller\\CartController:delete' => '?',
            'App\\Controller\\CartController:index' => '?',
            'App\\Controller\\IndexController:index' => '?',
            'App\\Controller\\ProductController:index' => '?',
            'App\\Controller\\ProductController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
