<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXNRxWxE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXNRxWxE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXNRxWxE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXNRxWxE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXNRxWxE\App_KernelDevDebugContainer([
    'container.build_hash' => 'XNRxWxE',
    'container.build_id' => 'f75cb145',
    'container.build_time' => 1641999808,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXNRxWxE');
