<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOMRTzE3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOMRTzE3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOMRTzE3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOMRTzE3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOMRTzE3\App_KernelDevDebugContainer([
    'container.build_hash' => 'OMRTzE3',
    'container.build_id' => '711d3b68',
    'container.build_time' => 1642080195,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOMRTzE3');
